const agents = [
  {name:'Atlas', role:'Orchestrator', model:'Dynamic frontier routing', letter:'✦', tone:'violet', desc:'Owns the plan, delegates the work and keeps the final answer coherent.', cap:'Coordination', score:'98'},
  {name:'Lumen', role:'Researcher', model:'Best available research model', letter:'R', tone:'teal', desc:'Finds current evidence, compares sources and timestamps every claim.', cap:'Evidence quality', score:'95'},
  {name:'Coda', role:'Builder', model:'Best available coding model', letter:'C', tone:'pink', desc:'Turns approved decisions into documents, code, workflows and tested outputs.', cap:'Implementation', score:'96'},
  {name:'Mosaic', role:'Multimodal analyst', model:'Best available vision model', letter:'G', tone:'gold', desc:'Reads images, PDFs, tables and visual context that text-only agents miss.', cap:'Multimodal work', score:'94'},
  {name:'Sage', role:'Strategy cell', model:'Best available reasoning model', letter:'S', tone:'blue', desc:'Builds scenarios, trade-offs and a clear recommendation—or a no-decision.', cap:'Decision quality', score:'97'},
  {name:'Aegis', role:'Security reviewer', model:'Independent review route', letter:'!', tone:'coral', desc:'Checks permissions, privacy, fraud, irreversible effects and hidden assumptions.', cap:'Risk detection', score:'99'},
  {name:'Verity', role:'Devil’s advocate', model:'Adversarial cross-check', letter:'V', tone:'violet', desc:'Tries to break the proposal before it reaches Davide for approval.', cap:'Challenge rate', score:'93'},
  {name:'Ledger', role:'Finance reviewer', model:'Best available analysis model', letter:'€', tone:'teal', desc:'Tests costs, downside, cash flow and whether the decision is affordable.', cap:'Numerical checks', score:'94'},
  {name:'Archivist', role:'Memory keeper', model:'Local policy + retrieval', letter:'◌', tone:'gold', desc:'Stores approved principles, outcomes, sources and lessons without blind retraining.', cap:'Continuity', score:'92'}
];
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
function showView(view){$$('.view').forEach(v=>v.classList.remove('active-view')); $(`#view-${view}`).classList.add('active-view'); $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); const titles={overview:'Good evening, Davide',team:'Meet your AI team',tasks:'The work queue',approvals:'Your approval desk',memory:'The office memory'}; $('#pageTitle').textContent=titles[view]||titles.overview; window.scrollTo({top:0,behavior:'smooth'});}
function renderTeam(){ $('#teamGrid').innerHTML=agents.map(a=>`<article class="team-card card"><div class="agent-head"><div class="agent-avatar ${a.tone}">${a.letter}</div><div><h3>${a.name}</h3><span class="role-tag">${a.role}</span></div></div><p>${a.desc}</p><span class="agent-model">${a.model}</span><div class="agent-capability">${a.cap}<b>${a.score}/100</b></div></article>`).join(''); }
function openModal(mode='brief',action=''){const b=$('#modalBackdrop'); b.classList.add('open'); b.setAttribute('aria-hidden','false'); $('#briefForm').hidden=mode!=='brief'; $('#approvalDecision').hidden=mode!=='approval'; if(mode==='approval'){const payment=action==='payment'; $('#modalEyebrow').textContent=payment?'PAYMENT · HIGH RISK':'DELETE · HIGH RISK'; $('#modalTitle').textContent='Your decision is required'; $('#modalCopy').textContent='The action is paused. Review the exact scope before releasing it.'; $('#decisionTitle').textContent=payment?'Pay € 850,00 to Edil Toscana SRL':'Archive 12 documents'; $('#decisionText').textContent=payment?'No funds will move until you approve this one-time request.':'The files will move to archive and remain restorable for 30 days.';}else{$('#modalEyebrow').textContent='NEW BRIEF';$('#modalTitle').textContent='What should the office work on?';$('#modalCopy').textContent='Atlas will break it into specialist tasks and show you the plan before anything sensitive happens.';setTimeout(()=>$('#briefInput').focus(),50)}}
function closeModal(){const b=$('#modalBackdrop');b.classList.remove('open');b.setAttribute('aria-hidden','true');$('#briefForm').reset();}
renderTeam();
$('#redButton').addEventListener('click',()=>{const b=$('#redButton');b.classList.add('pulse');setTimeout(()=>b.classList.remove('pulse'),600);showToast('Allerta: Aegis ha ordinato una torta. Nessuna azione critica rilevata.');});$('#coffeeButton').addEventListener('click',()=>{const prompts=['Quale agente mente meglio quando dice “ho quasi finito”?','Se il budget fosse infinito, quale problema risolveresti domani?','Quale decisione merita una passeggiata prima di una risposta?','Chi al tavolo ha bisogno di una pausa?'];showToast('Domanda del giorno: '+prompts[Math.floor(Math.random()*prompts.length)]);});$('#wormholeButton').addEventListener('click',()=>{showView('memory');showToast('Wormhole aperto: lezione futura caricata in anteprima.');});
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view))); $$('[data-view-target]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewTarget))); $('#newTaskBtn').addEventListener('click',()=>openModal());$('#newTaskBtn2').addEventListener('click',()=>openModal());$('#modalClose').addEventListener('click',closeModal);$('#modalCancel').addEventListener('click',closeModal);$('#modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal()});$('#openReview').addEventListener('click',()=>showView('approvals'));$$('.approve-open').forEach(b=>b.addEventListener('click',()=>{showView('approvals');openModal('approval',b.closest('.task-card').querySelector('h3').textContent.includes('Pay')?'payment':'delete')}));$$('[data-action]').forEach(b=>b.addEventListener('click',()=>openModal('approval',b.dataset.action)));$('#briefForm').addEventListener('submit',e=>{e.preventDefault();closeModal();showView('tasks');$('#taskCount').textContent='5';showToast('Brief ricevuto. Atlas sta preparando il piano.');});$('#decisionApprove').addEventListener('click',()=>{closeModal();showToast('Approvazione registrata. L’azione resta tracciata.');});$('#decisionReject').addEventListener('click',()=>{closeModal();showToast('Azione rifiutata e archiviata nel registro.');});$('#refreshModels').addEventListener('click',()=>showToast('Model board aggiornato: routing pronto.'));function showToast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)}
(function loadUniversalOffice(){if(document.getElementById('universalOfficeLoader'))return;const s=document.createElement('script');s.id='universalOfficeLoader';s.src='universal-office.js?v=2.0';s.defer=true;document.head.appendChild(s)})();
(function loadWeeklyLeague(){if(document.getElementById('weeklyLeagueLoader'))return;const s=document.createElement('script');s.id='weeklyLeagueLoader';s.src='weekly-league.js?v=1.0';s.defer=true;document.head.appendChild(s)})();
