(function(){
'use strict';
const STATE_KEY='the-office:hq:v1';
const PROFILES={
  Direttore:{icon:'👔',role:'Direttore',engine:'OpenAI · GPT-5.6 Sol',mode:'orchestrazione',fun:'Quello che entra in riunione e in 30 secondi decide chi deve fare cosa.',skills:['Routing','Priorità','Sintesi','Decisioni'],legacy:'Atlas'},
  Lumen:{icon:'🔎',role:'Ricerca',engine:'OpenAI · GPT-5.6 Sol + Web',mode:'ricerca verificata',fun:'Il collega con 27 tab aperte, ma stranamente sa sempre quale era quella giusta.',skills:['Web','Fonti','Fact-check','Dossier']},
  Coda:{icon:'💻',role:'Builder',engine:'OpenAI · GPT-5.6 Sol',mode:'coding & produzione',fun:'Se trova un bug alle 17:59, per lui la giornata è appena iniziata.',skills:['Codice','Documenti','Automazioni','Test']},
  Mosaic:{icon:'👁️',role:'Multimodale',engine:'OpenAI · GPT-5.6 Sol Vision',mode:'immagini & file',fun:'Legge anche lo screenshot inclinato, sfocato e mandato senza spiegazioni.',skills:['Immagini','PDF','Tabelle','Screenshot']},
  Sage:{icon:'♟️',role:'Strategia',engine:'OpenAI · GPT-5.6 Sol',mode:'reasoning',fun:'Pensa tre mosse avanti e poi chiede perché non ne abbiamo pensate cinque.',skills:['Scenari','Trade-off','Strategia','Decisioni']},
  Aegis:{icon:'🛡️',role:'Sicurezza',engine:'OpenAI · GPT-5.6 Sol',mode:'risk review',fun:'Quello che prima di premere “Invia” domanda: «Siamo proprio sicuri?»',skills:['Privacy','Permessi','Rischio','Azioni sensibili']},
  Verity:{icon:'😈',role:'Devil’s advocate',engine:'OpenAI · GPT-5.6 Sol',mode:'adversarial review',fun:'Il suo lavoro è rompere le idee. Se sopravvivono a lui, meritano rispetto.',skills:['Contestazione','Bias','Errori','Second opinion']},
  Ledger:{icon:'🧮',role:'Numeri & finanza',engine:'OpenAI · GPT-5.6 Sol',mode:'analisi quantitativa',fun:'Se manca un centesimo, non sa ancora dove sia, ma sa già che manca.',skills:['Calcoli','Finanza','Budget','Scenari']},
  Archivist:{icon:'🗃️',role:'Memoria',engine:'Memory + OpenAI · GPT-5.6 Sol',mode:'retrieval & continuity',fun:'Ricorda dove abbiamo messo “quella cosa” quando nessun altro ricorda cosa fosse.',skills:['Memoria','Contesto','Storico','Lezioni']}
};
const ROUTE_NAMES={Atlas:'Direttore'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function state(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch{return{}}}
function save(v){localStorage.setItem(STATE_KEY,JSON.stringify(v))}
function ensureCss(){if(document.querySelector('link[href^="interactive-office.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='interactive-office.css?v=3.0';document.head.appendChild(l)}
function mapped(name){return ROUTE_NAMES[name]||name}
function agentButton(name,p){return `<button class="hq-agent" data-agent="${esc(name)}" type="button"><span class="hq-avatar">${p.icon}</span><b>${esc(name)}</b><small>${esc(p.role)}</small><span class="hq-engine">${esc(p.engine.replace('OpenAI · ',''))}</span></button>`}
function sceneHtml(){return `<section class="hq-scene" id="hqScene"><div class="hq-head"><div><span class="eyebrow">INTERACTIVE HQ</span><h2>Entra nell’ufficio</h2><p>Clicca una persona per capire chi è, quale AI usa e affidarle un lavoro. Oppure dai l’incarico al Direttore: formerà il team adatto.</p></div><span class="hq-live"><i></i> DISPATCH OPERATIVO</span></div><div class="hq-room"><div class="hq-floor"></div><div class="hq-table"></div>${Object.entries(PROFILES).map(([n,p])=>agentButton(n,p)).join('')}<div class="hq-command"><div class="hq-command-card"><label for="hqBrief">INCARICO AL DIRETTORE</label><div class="hq-command-row"><input id="hqBrief" placeholder="Es. confronta tre preventivi e dimmi quale conviene..."/><button class="primary-btn" id="hqDispatch" type="button">Assegna →</button></div><div class="hq-statusline"><span id="hqTeamStatus">Team in attesa</span><span>azioni sensibili → approvazione</span><span>AI live → bridge sicuro da collegare</span></div></div></div></div></section>`}
function drawerHtml(){return `<div class="hq-backdrop" id="hqBackdrop"></div><aside class="hq-drawer" id="hqDrawer" aria-hidden="true"><div class="hq-drawer-head"><div><span class="eyebrow">DIPENDENTE AI</span><h2 style="margin:4px 0 0">Scheda personale</h2></div><button class="hq-drawer-close" id="hqClose" aria-label="Chiudi">×</button></div><div id="hqDrawerBody"></div></aside>`}
function insertScene(){if(document.getElementById('hqScene'))return;const overview=document.getElementById('view-overview');if(!overview)return;const anchor=document.getElementById('universalCommand')||overview.querySelector('.hero-row');anchor.insertAdjacentHTML('afterend',sceneHtml());document.body.insertAdjacentHTML('beforeend',drawerHtml())}
function renderState(){const s=state();document.querySelectorAll('.hq-agent').forEach(el=>{const a=s[el.dataset.agent];el.classList.toggle('working',a?.status==='working');el.classList.toggle('active',Boolean(a?.active))})}
function setWorking(names,title){const s=state();Object.keys(PROFILES).forEach(n=>{s[n]={...(s[n]||{}),active:false}});names.map(mapped).forEach(n=>{if(PROFILES[n])s[n]={...(s[n]||{}),active:true,status:'working',task:title,updated:Date.now()}});save(s);renderState();const label=document.getElementById('hqTeamStatus');if(label)label.textContent=`Team: ${names.map(mapped).join(' · ')}`}
function openAgent(name){const p=PROFILES[name];if(!p)return;const s=state()[name]||{};const body=document.getElementById('hqDrawerBody');body.innerHTML=`<div class="hq-profile"><span class="hq-avatar">${p.icon}</span><div><h3>${esc(name)}</h3><p>${esc(p.role)} · ${s.status==='working'?'sta lavorando':'disponibile'}</p></div></div><div class="hq-ai-card"><div class="hq-ai-top"><b>CHE AI È?</b><span>PROFILO AI</span></div><strong>${esc(p.engine)}</strong><p>Usata con profilo <b>${esc(p.mode)}</b>. Nell’interfaccia il personaggio rappresenta questa specializzazione, non un’AI misteriosa diversa.</p></div><div class="hq-fun">${esc(p.fun)}</div><div class="hq-capabilities">${p.skills.map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="hq-job"><label>DAI UN LAVORO A ${esc(name.toUpperCase())}</label><textarea id="hqAgentBrief" placeholder="Scrivi l’incarico..."></textarea><div class="hq-job-actions"><button class="primary-btn" id="hqAssignAgent">Assegna</button><button class="ghost-btn" id="hqRoundtable">Porta al tavolo</button></div></div><div class="office-principle"><strong>Stato reale:</strong> il dispatch, la coda, il routing e la persistenza funzionano già nel browser. Per far produrre a questi avatar risposte AI autonome dalla pagina serve ancora un backend sicuro: le chiavi non vanno mai messe in GitHub Pages.</div>`;document.getElementById('hqDrawer').classList.add('open');document.getElementById('hqBackdrop').classList.add('open');document.getElementById('hqDrawer').setAttribute('aria-hidden','false');document.getElementById('hqAssignAgent').onclick=()=>assignTo(name,false);document.getElementById('hqRoundtable').onclick=()=>assignTo(name,true)}
function closeDrawer(){document.getElementById('hqDrawer')?.classList.remove('open');document.getElementById('hqBackdrop')?.classList.remove('open');document.getElementById('hqDrawer')?.setAttribute('aria-hidden','true')}
function createWork(text,source){if(window.TheOfficeUniversal?.createWork)window.TheOfficeUniversal.createWork(text,source)}
function assignTo(name,roundtable){const input=document.getElementById('hqAgentBrief');const text=input?.value.trim();if(!text)return;const team=roundtable?[name,'Direttore','Verity']:[name];setWorking(team,text);createWork(text,`avatar:${name}`);closeDrawer();document.getElementById('hqScene')?.scrollIntoView({behavior:'smooth',block:'center'})}
function dispatch(){const input=document.getElementById('hqBrief');const text=input?.value.trim();if(!text)return;let plan=null;try{plan=window.TheOfficeUniversal?.routePlan?.(text)}catch{}const team=(plan?.route?.team||['Direttore','Lumen','Sage']).map(mapped);setWorking(team,text);createWork(text,'interactive-hq');input.value=''}
function bind(){document.querySelectorAll('.hq-agent').forEach(b=>b.addEventListener('click',()=>openAgent(b.dataset.agent)));document.getElementById('hqDispatch')?.addEventListener('click',dispatch);document.getElementById('hqBrief')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();dispatch()}});document.getElementById('hqClose')?.addEventListener('click',closeDrawer);document.getElementById('hqBackdrop')?.addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()})}
function patchUniversal(){if(!window.TheOfficeUniversal?.createWork||window.TheOfficeUniversal.__hqPatched)return;const original=window.TheOfficeUniversal.createWork.bind(window.TheOfficeUniversal);window.TheOfficeUniversal.createWork=function(text,source){let plan=null;try{plan=window.TheOfficeUniversal.routePlan(text)}catch{}const team=(plan?.route?.team||[]).map(mapped);if(team.length)setWorking(team,text);return original(text,source)};window.TheOfficeUniversal.__hqPatched=true}
function mount(){ensureCss();insertScene();bind();renderState();patchUniversal();setTimeout(patchUniversal,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
window.TheOfficeHQ={profiles:PROFILES,openAgent,dispatch,setWorking};
})();
