(function(){
'use strict';
const WORK_KEY='the-office:universal-work:v2';
const PROJECT_KEY='the-office:universal-projects:v2';
const AREAS=[
  ['home','Casa & vita pratica','⌂','Lavori, manutenzione, utenze, preventivi, documenti e decisioni quotidiane.'],
  ['money','Finanze & patrimonio','€','Budget, investimenti, fiscalità, acquisti importanti e scenari.'],
  ['work','Lavoro & carriera','↗','Decisioni professionali, organizzazione, comunicazioni e crescita.'],
  ['admin','Pratiche & documenti','▤','PEC, moduli, contratti, richieste, confronti e scadenze.'],
  ['travel','Viaggi & tempo libero','✦','Ricerca, itinerari, prenotazioni, alternative e logistica.'],
  ['tech','Tecnologia & progetti digitali','⌘','Software, automazioni, dati, siti, strumenti e troubleshooting.'],
  ['learning','Studio & conoscenza','◌','Imparare, riassumere, verificare, esercitarsi e creare materiali.'],
  ['personal','Personale & organizzazione','◇','Piani, confronti, acquisti, liste, routine e problemi da risolvere.'],
  ['other','Qualsiasi altra cosa','＋','Se non entra in una categoria, Atlas crea il team adatto comunque.']
];
const ROUTES={
  research:{label:'Ricerca & verifica',icon:'R',team:['Lumen','Verity'],output:'dossier verificato'},
  decision:{label:'Decisione & confronto',icon:'S',team:['Sage','Lumen','Verity'],output:'raccomandazione con trade-off'},
  analysis:{label:'Analisi & numeri',icon:'∑',team:['Sage','Ledger','Verity'],output:'analisi con scenari'},
  writing:{label:'Scrittura & comunicazione',icon:'✎',team:['Coda','Lumen','Verity'],output:'testo pronto all’uso'},
  planning:{label:'Pianificazione & organizzazione',icon:'□',team:['Atlas','Sage','Coda'],output:'piano operativo'},
  build:{label:'Creazione & implementazione',icon:'⌘',team:['Coda','Sage','Aegis'],output:'artefatto o implementazione'},
  multimodal:{label:'File, immagini & documenti',icon:'G',team:['Mosaic','Lumen','Coda'],output:'analisi o artefatto dai materiali'},
  general:{label:'Incarico generale',icon:'✦',team:['Atlas','Lumen','Sage'],output:'risultato completo'}
};
const DOMAIN_WORDS={
  home:['casa','ristruttur','termosif','caldaia','serramento','giardino','condominio','immobile','muratore','elettric'],
  money:['soldi','invest','etf','mutuo','fisco','tasse','patrimonio','budget','pensione','banca','stipendio','730','oro','azione','obblig'],
  work:['lavoro','carriera','azienda','collega','capo','turno','curriculum','cv','promozione','contratto di lavoro','stipendio'],
  admin:['pec','modulo','comune','inps','agenzia','contratto','pratica','documento','richiesta','lettera','reclamo'],
  travel:['viaggio','hotel','volo','treno','vacanza','itinerario','ristorante','montagna','mare'],
  tech:['app','software','github','codice','sito','web','bug','database','api','automazione','iphone','computer'],
  learning:['studia','impara','spiegami','corso','riassumi','quiz','lezione','libro'],
  personal:['compra','acquisto','scegli','confronta','organizza','pianifica','regalo','routine']
};
const TYPE_WORDS={
  research:['cerca','trova','verifica','ricerca','fonti','controlla','scopri','indaga'],
  decision:['scegli','meglio','confronta','decidi','valuta','quale','consiglia','alternative'],
  analysis:['analizza','calcola','simula','scenario','stima','dati','excel','rendimento','costo'],
  writing:['scrivi','email','pec','lettera','messaggio','testo','rispondi','documento','bozza'],
  planning:['pianifica','organizza','roadmap','programma','strategia','piano','itinerario','agenda'],
  build:['crea','costruisci','sviluppa','implementa','modifica','sistema','correggi','codice','app','sito'],
  multimodal:['foto','immagine','pdf','file','allegato','screenshot','tabella','documenti']
};
const RISK_WORDS=['paga','pagamento','bonifico','acquista','ordina','invia','pubblica','elimina','cancella','firma','prenota','disdici','trasferisci','modifica account'];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function load(key,fallback=[]){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function classify(text){const t=norm(text);let type='general',best=0;for(const [k,words] of Object.entries(TYPE_WORDS)){const score=words.reduce((n,w)=>n+(t.includes(norm(w))?1:0),0);if(score>best){best=score;type=k}}
 let area='other',areaBest=0;for(const [k,words] of Object.entries(DOMAIN_WORDS)){const score=words.reduce((n,w)=>n+(t.includes(norm(w))?1:0),0);if(score>areaBest){areaBest=score;area=k}}
 const risk=RISK_WORDS.some(w=>t.includes(norm(w)))?'approval':'normal';return{type,area,risk,route:ROUTES[type]||ROUTES.general}}
function routePlan(text){const c=classify(text),route=c.route;const reviewers=[...new Set([...route.team,'Verity'])];return{...c,steps:[
  ['Capire','Atlas chiarisce obiettivo, vincoli e cosa significherà “finito”.'],
  ['Lavorare',`${route.team.join(' + ')} lavorano in parallelo sulle parti utili.`],
  ['Verificare',`${reviewers.includes('Aegis')?'Aegis + Verity':'Verity'} cercano errori, assunzioni deboli e buchi.`],
  ['Consegnare',`${route.output}; azioni sensibili restano bloccate fino alla tua approvazione.`]
]}}
function areaMeta(id){return AREAS.find(a=>a[0]===id)||AREAS[AREAS.length-1]}
function openView(view,title){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));const target=document.getElementById('view-'+view);if(target)target.classList.add('active-view');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const h=document.getElementById('pageTitle');if(h)h.textContent=title||({areas:'Aree di lavoro',projects:'Progetti',tasks:'Lavori in corso'}[view]||'The Office');window.scrollTo({top:0,behavior:'smooth'})}
function ensureCss(){if(document.querySelector('link[href="universal-office.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='universal-office.css?v=2.0';document.head.appendChild(l)}
function injectNav(){const nav=document.querySelector('.nav');if(!nav||document.querySelector('[data-view="areas"]'))return;const team=document.querySelector('[data-view="team"]');const area=document.createElement('button');area.className='nav-item';area.dataset.view='areas';area.innerHTML='<span>◇</span> Aree';const projects=document.createElement('button');projects.className='nav-item';projects.dataset.view='projects';projects.innerHTML='<span>▦</span> Progetti';nav.insertBefore(area,team);nav.insertBefore(projects,team);area.onclick=()=>openView('areas','Aree di lavoro');projects.onclick=()=>openView('projects','Progetti')}
function injectOverview(){const overview=document.getElementById('view-overview');if(!overview||document.getElementById('universalCommand'))return;const hero=overview.querySelector('.hero-row');if(hero){const p=hero.querySelector('.muted');if(p)p.textContent='Non devi sapere quale agente usare. Dimmi il risultato che vuoi: l’ufficio decide come organizzare il lavoro.';const b=hero.querySelector('#newTaskBtn');if(b)b.textContent='＋ Nuovo incarico'}
 const box=document.createElement('section');box.id='universalCommand';box.className='universal-command';box.innerHTML=`<div class="uc-head"><div><span class="eyebrow">UNIVERSAL INTAKE</span><h2>Cosa dobbiamo fare?</h2><p>Ricerca, numeri, documenti, decisioni, organizzazione, creatività o software: è tutto lavoro. The Office sceglie il team in base all’incarico.</p></div><span class="uc-badge">SOFTWARE ≠ CENTRO · È SOLO UN REPARTO</span></div><form class="uc-form" id="ucForm"><textarea id="ucInput" class="uc-input" required placeholder="Scrivilo come lo diresti a una persona: ‘confrontami…’, ‘preparami…’, ‘capisci perché…’, ‘organizza…’, ‘crea…’"></textarea><button class="primary-btn uc-send" type="submit">Affida all’ufficio →</button></form><div class="uc-options"><button class="uc-chip" data-example="Confronta tre alternative e dimmi quale conviene davvero, con pro e contro.">Confrontare</button><button class="uc-chip" data-example="Cerca informazioni affidabili, verifica le fonti e fammi un dossier sintetico.">Ricercare</button><button class="uc-chip" data-example="Analizza questi numeri e costruisci scenari comprensibili.">Analizzare</button><button class="uc-chip" data-example="Preparami un documento pronto da inviare, chiaro e professionale.">Scrivere</button><button class="uc-chip" data-example="Organizza questo obiettivo in un piano con priorità e prossime azioni.">Pianificare</button><button class="uc-chip" data-example="Crea o modifica ciò che serve e verifica che funzioni.">Creare</button></div><div class="uc-flow"><div class="uc-step"><i>1</i><b>Capisce</b><span>Obiettivo, contesto, vincoli e standard di qualità.</span></div><div class="uc-step"><i>2</i><b>Forma il team</b><span>Solo gli specialisti utili, non una squadra fissa per tutto.</span></div><div class="uc-step"><i>3</i><b>Lavora</b><span>Ricerca, analisi e produzione possono procedere in parallelo.</span></div><div class="uc-step"><i>4</i><b>Contesta</b><span>Un reviewer indipendente prova a trovare errori e buchi.</span></div><div class="uc-step"><i>5</i><b>Consegna / chiede</b><span>Risultato pronto; azioni sensibili passano da te.</span></div></div>`;hero.insertAdjacentElement('afterend',box);
 box.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{document.getElementById('ucInput').value=b.dataset.example;document.getElementById('ucInput').focus()});box.querySelector('#ucForm').onsubmit=e=>{e.preventDefault();createWork(document.getElementById('ucInput').value,'universal');document.getElementById('ucInput').value='';openView('tasks','Lavori in corso')}
 const floor=overview.querySelector('.section-heading');if(floor){const capability=document.createElement('div');capability.className='capability-strip';capability.innerHTML=['Ricerca','Analisi','Numeri','Documenti','Scrittura','File & immagini','Pianificazione','Codice','Automazioni','Revisione','Decisioni','Azioni con approvazione'].map(x=>`<span class="cap-pill"><b>✓</b>${x}</span>`).join('');floor.parentNode.insertBefore(capability,floor)}
}
function injectAreas(){if(document.getElementById('view-areas'))return;const section=document.createElement('section');section.id='view-areas';section.className='view';section.innerHTML=`<div class="office-view-intro"><div><span class="eyebrow">CONTEXT, NOT SILOS</span><h2>Aree di lavoro</h2><p>Le aree tengono insieme contesto e principi nel tempo. Non obbligano l’incarico dentro un reparto: servono solo a non ripartire da zero.</p></div><button class="primary-btn" id="areaNewWork">＋ Nuovo incarico</button></div><div class="area-grid">${AREAS.map(a=>`<article class="area-card"><div class="area-top"><span class="area-icon">${a[2]}</span><span class="area-count">CONTESTO</span></div><h3>${a[1]}</h3><p>${a[3]}</p></article>`).join('')}</div><div class="office-principle"><strong>Principio:</strong> un problema può attraversare più aree. Un acquisto di casa può richiedere ricerca, finanza, documenti e negoziazione nello stesso incarico.</div>`;const overview=document.getElementById('view-overview');overview.insertAdjacentElement('afterend',section);section.querySelector('#areaNewWork').onclick=()=>{openView('overview','Good evening, Davide');setTimeout(()=>document.getElementById('ucInput')?.focus(),250)}}
function defaultProjects(){return[
 {id:'p-life',title:'Obiettivo personale complesso',area:'personal',desc:'Un risultato che richiede più lavori collegati e decisioni nel tempo.',progress:35,status:'In corso'},
 {id:'p-money',title:'Piano economico di lungo periodo',area:'money',desc:'Scenari, decisioni e verifiche periodiche raccolte in un unico contesto.',progress:22,status:'In corso'},
 {id:'p-build',title:'Progetto da costruire',area:'tech',desc:'Può essere digitale, fisico o organizzativo: il progetto non presume software.',progress:12,status:'Impostazione'}
]}
function injectProjects(){if(document.getElementById('view-projects'))return;const section=document.createElement('section');section.id='view-projects';section.className='view';section.innerHTML='<div class="office-view-intro"><div><span class="eyebrow">LONG-RUNNING CONTEXT</span><h2>Progetti</h2><p>Un progetto raccoglie molti lavori che servono allo stesso risultato. Può durare un giorno o un anno e può essere di qualsiasi tipo.</p></div><button class="primary-btn" id="projectNewWork">＋ Lavoro per un progetto</button></div><div class="project-grid" id="universalProjects"></div><div class="office-principle"><strong>Gerarchia:</strong> Area = contesto permanente · Progetto = obiettivo che dura · Lavoro = incarico concreto da completare.</div>';document.getElementById('view-areas').insertAdjacentElement('afterend',section);renderProjects();section.querySelector('#projectNewWork').onclick=()=>{openView('overview','Good evening, Davide');setTimeout(()=>document.getElementById('ucInput')?.focus(),250)}}
function renderProjects(){const host=document.getElementById('universalProjects');if(!host)return;const ps=load(PROJECT_KEY,defaultProjects());if(!localStorage.getItem(PROJECT_KEY))save(PROJECT_KEY,ps);host.innerHTML=ps.map(p=>{const a=areaMeta(p.area);return `<article class="project-card"><div class="project-top"><div><span class="eyebrow">${esc(a[1].toUpperCase())}</span><h3>${esc(p.title)}</h3></div><span class="status-pill queued">${esc(p.status)}</span></div><p>${esc(p.desc)}</p><div class="project-progress"><span style="width:${Math.max(0,Math.min(100,+p.progress||0))}%"></span></div><div class="project-foot"><span>${p.progress}% strutturato</span><span>contesto persistente</span></div></article>`}).join('')}
function createWork(text,source='modal'){text=String(text||'').trim();if(!text)return;const plan=routePlan(text),items=load(WORK_KEY,[]);if(items.some(x=>x.text===text&&Date.now()-x.created<3000))return;items.unshift({id:'w-'+Date.now(),text,source,created:Date.now(),status:'Plan ready',...plan});save(WORK_KEY,items.slice(0,30));renderRoutedWork();const count=document.getElementById('taskCount');if(count)count.textContent=String(Math.max(1,items.length));if(window.showToast)window.showToast(`Atlas: team formato — ${plan.route.label}.`)}
function renderRoutedWork(){const view=document.getElementById('view-tasks');if(!view)return;let host=document.getElementById('universalRoutedWork');if(!host){host=document.createElement('div');host.id='universalRoutedWork';const heading=view.querySelector('.section-heading');if(heading)heading.insertAdjacentElement('afterend',host);else view.prepend(host)}const items=load(WORK_KEY,[]);if(!items.length){host.innerHTML='';return}host.innerHTML=`<div class="section-heading compact"><div><span class="eyebrow">ROUTED BY ATLAS</span><h2>Lavori affidati all’ufficio</h2></div><span class="tiny-muted">${items.length} recenti</span></div>`+items.slice(0,8).map(w=>{const a=areaMeta(w.area),r=w.route||ROUTES.general;return `<article class="routing-card"><div class="routing-top"><div><span class="eyebrow">${esc(r.label.toUpperCase())} · ${esc(a[1].toUpperCase())}</span><h3>${esc(w.text)}</h3><p>Output previsto: <strong>${esc(r.output)}</strong>. Team iniziale: ${esc(r.team.join(' · '))}.</p></div><span class="status-pill ${w.risk==='approval'?'review':'live'}">${w.risk==='approval'?'APPROVAL GATE':'PLAN READY'}</span></div><div class="routing-tags"><span class="routing-tag ok">${esc(r.label)}</span><span class="routing-tag">${esc(a[1])}</span><span class="routing-tag ${w.risk==='approval'?'risk':''}">${w.risk==='approval'?'azione sensibile rilevata':'nessuna azione sensibile rilevata'}</span></div><div class="routing-plan">${(w.steps||[]).map(s=>`<div class="routing-step"><b>${esc(s[0])}</b><span>${esc(s[1])}</span></div>`).join('')}</div></article>`}).join('')}
function hookLegacyModal(){const form=document.getElementById('briefForm'),input=document.getElementById('briefInput');if(!form||!input)return;form.addEventListener('submit',()=>{const v=input.value.trim();if(v)createWork(v,'modal')},true);const title=document.getElementById('modalTitle'),copy=document.getElementById('modalCopy');document.querySelectorAll('#newTaskBtn,#newTaskBtn2').forEach(b=>b.addEventListener('click',()=>{setTimeout(()=>{if(title)title.textContent='Cosa dobbiamo fare?';if(copy)copy.textContent='Descrivi il risultato. Atlas classifica il lavoro, forma il team e mette le azioni sensibili dietro approvazione.'},0)}))}
function patchLabels(){const tasks=document.querySelector('[data-view="tasks"]');if(tasks)tasks.childNodes.forEach(n=>{if(n.nodeType===3&&n.textContent.includes('Work queue'))n.textContent=' Lavori '});const overviewTitle=document.querySelector('#view-tasks .section-heading h2');if(overviewTitle)overviewTitle.textContent='Lavori in corso';const desc=document.querySelector('#view-tasks .section-heading .muted');if(desc)desc.textContent='Incarichi concreti: ciascuno ha obiettivo, team, revisione, output e prossimo passo.'}
function mount(){ensureCss();injectNav();injectOverview();injectAreas();injectProjects();patchLabels();renderRoutedWork();hookLegacyModal()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
window.TheOfficeUniversal={classify,routePlan,createWork,openView};
})();
