import { VERSION, AGENTS, AREAS, esc } from './core.mjs';
import { BENCHMARKS, CAPABILITIES } from './benchmarks.mjs';

export function shell() {
  return `<div class="shell">
  <header class="topbar"><a class="brand" href="./"><span class="brand-mark">✦</span><span>The Office<small>IL TUO UFFICIO AI</small></span></a>
    <nav class="tabs" aria-label="Schermate"><button class="tab active" data-view="office" aria-current="page">Ufficio</button><button class="tab" data-view="details">Dettagli <span class="tiny-dot"></span></button></nav>
    <div class="owner"><span class="owner-avatar">D</span><span>Davide<small>Le decisioni sono tue</small></span></div>
  </header><div id="storage-warning" class="notice error" hidden></div>
  <section id="screen-office" class="screen">
    <div class="intro"><div><p class="eyebrow" id="today"></p><h1>Le idee entrano.<br><span>Il lavoro prende forma.</span></h1><p>Un Direttore, specialisti e un posto per ogni incarico.</p></div>
    <div class="office-state"><span class="signal" id="signal"></span><span id="health-label">Verifica del motore…</span><button class="text-button" data-action="health" aria-label="Ricontrolla il motore">↻</button></div></div>
    <div class="floor-grid"><section class="room" aria-label="Tavola rotonda degli agenti">
      <div class="room-top"><span>THE OFFICE / PIANO 01</span><span id="room-activity">Ufficio in attesa</span></div>
      <div class="windows" aria-hidden="true"><i></i><i></i><i></i></div>
      <div class="noticeboard"><span>LAVAGNA DEL DIRETTORE</span><b id="board-title">Si comincia da un’idea.</b><small id="board-copy">Qual è il prossimo risultato che vuoi ottenere?</small></div>
      <div class="plant plant-left" aria-hidden="true">♧</div><div class="plant plant-right" aria-hidden="true">♧</div>
      <div class="round-table" aria-hidden="true"><span>✦</span><div class="table-note">un passo<br>alla volta</div><i class="coffee"></i></div>
      <div class="people">${AGENTS.map((a, i) => `<button class="person p${i}" style="--agent:${a.color}" data-agent="${a.id}" aria-label="Scheda di ${a.id}"><span class="avatar"><i class="avatar-face"></i><span>${a.icon}</span></span><b>${a.id}</b><small>${a.role}</small><em>Disponibile</em></button>`).join('')}</div>
      <div class="room-bottom"><button class="coffee-button" data-action="coffee">☕ Pausa caffè</button><span>Gli avatar rappresentano ruoli.<br>Le esecuzioni compaiono nel risultato.</span><button class="stop-button" data-action="stop">■ Ferma ufficio</button></div>
    </section>
    <aside class="brief-card"><div class="card-top"><span class="eyebrow">UN NUOVO INCARICO</span><span class="mono">01 →</span></div><h2>Cosa dobbiamo fare?</h2><p>Scrivilo come lo diresti a una persona.</p>
      <form id="brief-form"><label class="sr-only" for="brief">Descrivi l’incarico</label><textarea id="brief" rows="5" maxlength="16000" placeholder="Confronta queste alternative e aiutami a scegliere…" required></textarea>
        <div class="materials-toolbar"><label class="material-picker">＋ Aggiungi testo<input type="file" id="material-file" accept=".txt,.md,.csv,.json" multiple></label><span>TXT · MD · CSV · JSON</span></div><div id="materials-list"></div><div class="examples"><button type="button" data-example="Confronta due preventivi: elenca i criteri e le informazioni che servono per scegliere.">Confrontare</button><button type="button" data-example="Prepara una bozza di email professionale per chiedere un aggiornamento su un progetto.">Scrivere</button><button type="button" data-example="Organizza un piano di studio di quattro settimane con obiettivi e verifiche.">Organizzare</button></div>
        <div class="field-row"><label>Area<select id="area"><option value="auto">Automatica</option>${AREAS.map(a => `<option>${a}</option>`).join('')}</select></label><label>Priorità<select id="priority"><option value="normal">Normale</option><option value="high">Alta</option></select></label></div>
        <details class="brief-options"><summary>Contesto e modalità</summary><label>Progetto<input id="project" maxlength="100" placeholder="Es. nuova casa, studio, lavoro"></label><label>Materiale<select id="sensitivity"><option value="public">Pubblico / non riservato</option><option value="private">Riservato → gateway personale</option></select></label><label>Revisione<select id="review-mode"><option value="fast">Risposta rapida · una chiamata</option><option value="roundtable">Tavola rotonda · specialisti e controprova</option><option value="independent">Modelli distinti → gateway personale</option></select></label><div id="memory-select"></div></details>
        <div id="plan-preview" class="plan-preview"></div><button id="send" class="primary" type="submit">Affida il lavoro <span>↗</span></button><button type="button" class="draft-button" data-action="draft">Salva solo una bozza locale</button>
      </form><p class="privacy-copy" id="privacy-copy"></p>
    </aside></div>
    <nav class="mobile-jumps" aria-label="Vai nell’ufficio"><button data-action="new-brief">＋ Incarico</button><button data-action="desk">▱ Lavori</button><button data-action="team">✦ Team</button></nav><div class="work-grid" id="desk"><div id="project-chips" class="project-chips"></div><section class="work-panel"><div class="section-top"><div><span class="eyebrow">SULLA SCRIVANIA</span><h2>I tuoi lavori <span id="job-count">0</span></h2></div><button class="text-button" data-action="resume" id="resume" hidden>Riattiva ufficio →</button></div>
      <div class="queue-tools"><label class="sr-only" for="search">Cerca nei lavori</label><input id="search" type="search" placeholder="Cerca incarico, area o progetto"><label class="sr-only" for="filter">Filtra per stato</label><select id="filter"><option value="all">Tutti</option><option value="active">In corso</option><option value="ready">Con risultato</option><option value="attention">Da rivedere</option><option value="draft">Bozze</option><option value="archived">Archiviati</option></select></div><div id="job-list" class="job-list"></div>
    </section><section class="result-panel" id="result-panel" aria-label="Risultato selezionato"><div id="result"></div></section></div>
  </section>
  <section id="screen-details" class="screen" hidden>
    <div class="details-heading"><div><p class="eyebrow">IL LAVORO, CON TRASPARENZA</p><h1>Dietro le quinte.</h1><p>Controlli, memoria e capacità effettive dell’ufficio.</p></div><span class="version">V${VERSION}</span></div>
    <div id="metrics" class="metrics"></div><div class="details-grid">
      <section class="detail-card"><span class="eyebrow">CONNESSIONE</span><h2>Il motore dell’ufficio</h2><div id="connection-status"></div><div id="model-observed"></div><form id="settings-form"><label>Motore<select id="engine"><option value="legacy">Gratuito · solo materiale pubblico</option><option value="secure">Gateway personale protetto</option></select></label><div id="secure-fields" hidden><label>URL del tuo gateway<input type="url" id="gateway-url" placeholder="https://…compute.c-5.us-east-2.aws.neon.tech"></label><label>Token della sessione personale<input type="password" id="session-token" autocomplete="off" placeholder="Resta solo in memoria fino alla chiusura"></label><p class="muted">Il token dell’ufficio è diverso dalla chiave del provider. La chiave del provider va configurata solo sul server.</p></div><button class="secondary" type="submit">Applica e verifica</button><button class="text-button" type="button" data-action="logout">Scollega sessione</button></form></section>
      <section class="detail-card"><span class="eyebrow">MEMORIA SELETTIVA</span><h2>Solo ciò che approvi.</h2><p class="muted">Note su questo dispositivo, con data e origine. Nessun addestramento automatico. Seleziona le note da usare in ogni incarico protetto.</p><form id="memory-form"><label for="memory-text" class="sr-only">Nota da ricordare</label><textarea id="memory-text" maxlength="2000" rows="3" placeholder="Una preferenza, una regola o una lezione utile…" required></textarea><button class="secondary" type="submit">Approva e ricorda</button></form><div id="memory-list"></div></section>
      <section class="detail-card wide"><span class="eyebrow">CAPACITÀ VERIFICABILI</span><h2>Cosa può fare, oggi.</h2><div class="table-wrap"><table><thead><tr><th>Funzione</th><th>Stato</th><th>Significato pratico</th></tr></thead><tbody>${CAPABILITIES.map(c => `<tr><th>${esc(c[0])}</th><td>${esc(c[1])}</td><td>${esc(c[2])}</td></tr>`).join('')}</tbody></table></div></section>
      <section class="detail-card wide"><span class="eyebrow">BENCHMARK INTERNAZIONALE · 13 SET 2026</span><h2>Da chi prendiamo spunto.</h2><p class="muted">Ordine di utilità per The Office: una valutazione progettuale, non una classifica mondiale di mercato. Prodotti e framework hanno ruoli diversi.</p><div class="benchmark-list">${BENCHMARKS.map(b => `<a href="${b.url}" target="_blank" rel="noopener noreferrer"><span class="rank">0${b.rank}</span><div><strong>${b.name}</strong><small>${b.category}</small><p>${b.take}</p></div><span>↗</span></a>`).join('')}</div></section>
      <section class="detail-card"><span class="eyebrow">MISURARE PER MIGLIORARE</span><h2>La corona si guadagna.</h2><div id="league"></div><p class="muted">Il feedback misura utilità percepita. Non dimostra accuratezza e non cambia i modelli automaticamente.</p></section>
      <section class="detail-card"><span class="eyebrow">IL TUO CONTROLLO</span><h2>Salva, rivedi, recupera.</h2><p class="muted">Lo storico è locale, non cifrato dall’app e non sincronizzato fra dispositivi. L’esportazione include testi e note; conserva il file con cura.</p><div class="button-row"><button class="secondary" data-action="export-all">Esporta archivio JSON</button><button class="secondary" data-action="raw-export">Esporta dati originali</button></div><label class="import-label">Importa un archivio di The Office<input type="file" id="import-file" accept="application/json,.json"></label><div id="import-review"></div></section>
      <section class="detail-card wide"><span class="eyebrow">REGISTRO LOCALE</span><h2>Che cosa è successo.</h2><p class="muted">Registro diagnostico di questo dispositivo. Non è un audit immutabile.</p><div id="audit" class="audit"></div></section>
    </div>
  </section><footer><span>✦ The Office <b>V${VERSION}</b></span><span>Il criterio prima del rumore.</span><button class="text-button" data-action="top">Torna su ↑</button></footer></div>`;
}
